version: "3"
services:
    react-app:
        container_name: anime
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8084:80
        expose:
            - "8084"
        restart: unless-stopped
